name: Laravel Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo_sqlite
          tools: composer:v2

      - name: Instalar dependências do Laravel
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Criar arquivo `.env`
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=/tmp/database.sqlite" >> .env

      - name: Criar banco de dados SQLite
        run: touch /tmp/database.sqlite

      - name: Rodar migrações
        run: php artisan migrate --force

      - name: Executar testes
        run: php artisan test
